const API='';const statuses=['Not Started','Researching','People Found','Emails Sent','Replied','Closed'];let companies=[],contacts=[],chart,reminderMode=false;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw Error((await r.json()).detail||'Request failed');return r.status===204?null:r.json()}
function fillStatuses(){['company-status','contact-status','company-form-status','contact-form-status'].forEach(id=>{const e=$('#'+id);if(!e)return;const first=e.options.length?e.options[0].text:'';e.innerHTML=first.includes('All')?'<option value="">'+first+'</option>':'';statuses.forEach(s=>e.insertAdjacentHTML('beforeend',`<option value="${esc(s)}">${esc(s)}</option>`))})}
function pill(s){return `<span class="pill status-${s.toLowerCase().replaceAll(' ','-')}">${esc(s)}</span>`}
async function loadCompanies(){const q=new URLSearchParams();if($('#company-tier').value)q.set('tier',$('#company-tier').value);if($('#company-priority').value)q.set('priority',$('#company-priority').value);if($('#company-status').value)q.set('status',$('#company-status').value);$('#companies-body').innerHTML='<tr><td colspan="7" class="empty">Loading...</td></tr>';companies=await api('/companies?'+q);$('#companies-body').innerHTML=companies.length?companies.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.tier)}</td><td>${esc(c.priority)}</td><td>${pill(c.status)}</td><td>${c.people_found}</td><td>${c.emails_sent}</td><td class="actions"><button onclick="editCompany(${c.id})">✎</button><button onclick="removeCompany(${c.id})">🗑</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No companies yet — add your first one</td></tr>';syncCompanyOptions()}
async function loadContacts(){const q=new URLSearchParams();if($('#contact-company').value)q.set('company_id',$('#contact-company').value);if($('#contact-status').value)q.set('status',$('#contact-status').value);$('#contacts-body').innerHTML='<tr><td colspan="8" class="empty">Loading...</td></tr>';contacts=await api('/contacts?'+q);const rows=await Promise.all(contacts.map(async c=>{const d=await api(`/contacts/${c.id}/days-since-sent`);const co=companies.find(x=>x.id===c.company_id);return {...c,days:d.days_since_sent,company:co?.name||'—'}}));$('#contacts-body').innerHTML=rows.length?rows.map(c=>`<tr class="${c.days>=5&&c.status!=='Replied'?'followup':''}"><td><strong>${esc(c.first_name+' '+c.last_name)}</strong></td><td>${esc(c.company)}</td><td>${esc(c.role_title)}</td><td>${pill(c.status)}</td><td>${c.days??'—'}</td><td>${c.opened?'✓':'✗'}</td><td>${c.replied?'✓':'✗'}</td><td class="actions"><button onclick="editContact(${c.id})">✎</button><button onclick="removeContact(${c.id})">🗑</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No contacts yet — add your first one</td></tr>'}
function syncCompanyOptions(){const e=$('#contact-company');const current=e.value;e.innerHTML='<option value="">All companies</option>'+companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(current)e.value=current;const form=$('#contact-form [name=company_id]');form.innerHTML='<option value="">Select company</option>'+companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
async function loadDashboard(){const s=await api('/stats/summary'),t=await api('/stats/by-tier');$('#stats').innerHTML=[['Total Companies',s.total_companies],['Total Contacts',s.total_contacts],['Emails Sent',s.total_emails_sent],['Reply Rate',s.reply_rate+'%']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');if(chart)chart.destroy();chart=new Chart($('#tier-chart'),{type:'bar',data:{labels:t.map(x=>x.tier),datasets:[{label:'Emails sent',data:t.map(x=>x.emails_sent),backgroundColor:'#4F46E5',borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}})}
function openModal(id,obj){const m=$('#'+id),f=m.querySelector('form');f.reset();f.querySelector('[name=id]').value=obj?.id||'';if(obj)Object.entries(obj).forEach(([k,v])=>{const e=f.querySelector(`[name=${k}]`);if(e)e.value=typeof v==='boolean'?String(v):v??''});m.classList.add('open')}
function closeModals(){$$('.modal.open')?.classList.remove('open')};function $$(s){return document.querySelectorAll(s)}
window.editCompany=id=>openModal('company-modal',companies.find(c=>c.id===id));window.editContact=id=>openModal('contact-modal',contacts.find(c=>c.id===id));
window.removeCompany=async id=>{if(confirm('Delete this company and its contacts?')){await api('/companies/'+id,{method:'DELETE'});await loadCompanies();await loadContacts();toast('Company deleted')}};window.removeContact=async id=>{if(confirm('Delete this contact?')){await api('/contacts/'+id,{method:'DELETE'});await loadContacts();toast('Contact deleted')}};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function formData(f){const o=Object.fromEntries(new FormData(f));['people_found','emails_sent','company_id'].forEach(k=>{if(k in o)o[k]=Number(o[k])});['opened','replied'].forEach(k=>{if(k in o)o[k]=o[k]==='true'});return o}
async function submitForm(f,path){const err=f.querySelector('.form-error');err.textContent='';const data=formData(f);if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)){err.textContent='Enter a valid email address.';return}try{const id=data.id;delete data.id;await api(path+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(data)});f.closest('.modal').classList.remove('open');await loadCompanies();await loadContacts();toast(id?'Updated successfully':'Created successfully')}catch(e){err.textContent=e.message}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='dashboard')loadDashboard()});document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));document.querySelectorAll('.close').forEach(b=>b.onclick=closeModals);document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});['company-tier','company-priority','company-status'].forEach(id=>$('#'+id).onchange=loadCompanies);['contact-company','contact-status'].forEach(id=>$('#'+id).onchange=loadContacts);$('#company-form').onsubmit=e=>{e.preventDefault();submitForm(e.target,'/companies')};$('#contact-form').onsubmit=e=>{e.preventDefault();submitForm(e.target,'/contacts')};
fillStatuses();loadCompanies().then(loadContacts);
async function loadPipeline(){const all=await api('/contacts');const reminders=new Set((await api('/reminders')).map(x=>x.contact_id));const enriched=await Promise.all(all.map(async c=>{const d=await api(`/contacts/${c.id}/days-since-sent`);const company=companies.find(x=>x.id===c.company_id);return {...c,days:d.days_since_sent,company,needsFollowup:reminders.has(c.id)}}));const board=$('#pipeline-board');board.innerHTML=statuses.map(s=>`<div class="pipeline-column"><h3>${esc(s)} <span>(${enriched.filter(c=>c.status===s).length})</span></h3><div class="pipeline-cards" data-status="${esc(s)}">${enriched.filter(c=>c.status===s).map(c=>`<div class="pipeline-card priority-${String(c.company?.priority||'Medium').toLowerCase()}" data-id="${c.id}"><strong>${esc(c.first_name+' '+c.last_name)}${c.needsFollowup?' <span class="warning" title="Needs follow-up">⚠</span>':''}</strong><small>${esc(c.company?.name||'—')}</small><small>${c.days==null?'Not sent':c.days+' days since sent'}</small></div>`).join('')}</div></div>`).join('');board.querySelectorAll('.pipeline-cards').forEach(container=>new Sortable(container,{group:'pipeline',animation:150,onEnd:async event=>{const card=event.item,newStatus=event.to.dataset.status,oldContainer=event.from,oldIndex=event.oldIndex,oldStatus=event.from.dataset.status;if(newStatus===oldStatus)return;try{await api(`/contacts/${card.dataset.id}/status`,{method:'PATCH',body:JSON.stringify({status:newStatus})});await loadPipeline();loadReminderBadge()}catch(error){oldContainer.insertBefore(card,oldContainer.children[oldIndex]||null);toast('Could not update status; change rolled back')}}}))}
document.querySelector('[data-view="pipeline"]').addEventListener('click',loadPipeline);
const loadContactsAll=loadContacts;loadContacts=async()=>{await loadContactsAll();if(reminderMode){const ids=new Set((await api('/reminders')).map(x=>x.contact_id));document.querySelectorAll('#contacts-body tr').forEach((row,i)=>{if(!ids.has(contacts[i]?.id))row.remove()});if(!ids.size)$('#contacts-body').innerHTML='<tr><td colspan="8" class="empty">No contacts need follow-up</td></tr>'}};async function loadReminderBadge(){const reminders=await api('/reminders');$('#reminder-badge span').textContent=reminders.length}$('#reminder-badge').onclick=async()=>{reminderMode=true;document.querySelector('[data-view="contacts"]').click();await loadContacts()};loadReminderBadge();
